### ISSUE TITLE
Probably just a user thing but NTS-1 editor in Chrome...

### ISSUE THREAD

**Issue by wrightflyer** [oscarrc/nts-web#10]
I just wanted to try the web editor for NTS-1 but after I say "Allow" in Chrome 87 the Settings/Output drop list has no MIDI devices listed and yet other (desktop not web) apps that access MIDI can see it as a possible output.

Is there any way to debug this to know why Chrome can't "see" it (or any other MIDI device)?

BTW I almost always have LoopBe1 running so MIDI lists almost always list that as an input and output and yet Chrome doesn't list that either.

**Comment by wrightflyer** [comment]
Sorry for the noise - rebooted Win10 and now Chrome sees MIDI devices. Gotta love MIcrosoft!

**Comment by oscarrc** [comment]
Hi. 

You should only see NTS-1 devices at the moment. Please, tell me if you see other devices. 

Keep in mind that the device should be plugged in before running the app (or it needs a refresh after plug it in).
