### ISSUE TITLE
Rename the Patches

### ISSUE THREAD

**Issue by Velocet** [oscarrc/nts-web#24]
I cannot thank you enough for this little tool!

Do you think it's possible to make a third option to not only Import/Export the patches but to also rename them in the app? So when i load a complete set that i know right from the start what they are.

**Comment by oscarrc** [comment]
Do you mean change the button labels from "patch 1" to the actual patch name?

If so I can look into it

**Comment by Velocet** [comment]
Yeah .. sorry for the crooked english .. and you are right: i meant the button labels :)
