### ISSUE TITLE
Bugs and UX improvement on sequencer

### ISSUE THREAD

**Issue by mytea** [oscarrc/nts-web#26]
I really loved this, this project feels like I haven't waisted miney for this synth. 
 
• Mobile version has many crashes during sequencing (Samsung S7 & 1+One). How can I send logs for debugging?

• Sequencing is a great feature but not so easy to compose. (Smartphone & PC version)

If I can use I it, I will buy a NTS-1... not a coffee 😀
Many thanks for this great app.

**Comment by oscarrc** [comment]
Hi @mytea thanks for the feedback.

The mobile app is simply a webview wrapper over the web app, so yeah it crashes sometimes and I don't really now why.

Regarding sequencing I've to rewrite the app to change the way it handles MIDI, so I've thinking to go with a more traditional 16 step sequencer with n banks and side chaining capabilites.

It might take some time though.
