### ISSUE TITLE
The image for the "Scale" encoder in the ARP section should be a small encoder

### ISSUE THREAD

**Issue by computrav** [oscarrc/nts-web#36]
I suspect it was a copy/paste issue, but the ARP "Scale" encoder is the larger silver one (from selector.png sprite) in the UI, whereas I think it was supposed to be the smaller black one (knob.png sprite).
![nts-web-knob issue](https://user-images.githubusercontent.com/366410/212346894-c6d32d5f-98e5-4dbe-b4bb-4fb3386acc06.png)

**Comment by oscarrc** [comment]
@computrav First of all, thank you for taking the time to contribute.

What makes you think a knob would be better suited for that? As far as my design choices are, "selectors" are used for CCs that accept discrete values and knobs for CCs that expect a value in a range. It has nothing to do with simetry or anything like that if that's what concern you.

NTS-1 arp scale (CC 118, or "ARP.PATTERN" as is referred to in NTS-1 midi implementation chart) only accepts a set of 5 values so, I think a selector fits better here. 

What do you think? Does it make sense?

**Comment by computrav** [comment]
OK, I think I see my confusion... it was because I was trying to draw parallels between the UI and the physical NTS-1. On the NTS_1, when you hold down ARP and change TYPE, it corresponds to the TYPE knob in the UI. That obviously makes sense. However, I mistakenly thought the "SCALE" knob corresponded to the "A" knob on the NTS-1, which of course isn't the case. This is actually my first day using the NTS-1. :)

HOWEVER, in realizing the above, I think I found an actual bug relating to switching the ARP chord types. I'll cut a diff issue for that.

So I think this issue can be closed out and my pull request ignored. :)

**Comment by computrav** [comment]
User confusion, not actually a bug.
