### ISSUE TITLE
Various inconsistencies with physical NTS-1 button/encoder changes vs NTS-Web

### ISSUE THREAD

**Issue by computrav** [oscarrc/nts-web#38]
# MOD, DELAY, & REVERB Type Settings
The linkage between the NTS-1 and NTS-web when changing TYPE for both MOD and DELAY are a bit buggy. For example with MOD, I can't get NTS-Web to show "Chorus", when I go far to the right (Phaser), NTS-web shows "Unknown. I'm not sure if this is related to having custom MODs on the NTS-1 or not (I'm still completely stock at the moment). Same oddities with DELAY & REVERB

# OSC TYPE Setting
1. When you change TYPE to **VPM** on the NTS-1, the NTS-Web TYPE selector is set to **SQUARE** (or at least, is not set to VPM)

# ARP Chord Scale Settings
1. When you press ARP+MOD on the NTS-1, the ARP chord type on the NTS-1 is set to **Major Aug**, but on NTS-web, the "SCALE" selector value is incorrectly set to **Major Sus**.
2. When you press ARP+DELAY on the NTS-1, the ARP chord type on the NTS-1 is set to **Minor Triad**, but on NTS-web, the "SCALE" selector value is incorrectly set to **Major Augmented**

**For reference, changing ARP chord type, per the NTS-1 manual:**
- ARP + OSC = Octave
- ARP + FILTER = Major Triad
- ARP + EG = Major Sus
- ARP + MOD = Major Aug
- ARP + DELAY = Minor Triad
- ARP + REVERB = Minor Dim

**Comment by oscarrc** [comment]
1. User OSC and Effects: I'm aware of this and already working on it. If you move the selector one step it should fix itself. I'm using some library for the knobs which is giving me problems. BTW does it still happen if you plug in the NTS-1 before starting the app?
2. Arp Chord Scale Setting: I don't see any problem here, at first glance seems to work well on my unit.

Could you provide which OS and browser do you use?

**Comment by computrav** [comment]
> **BTW does it still happen if you plug in the NTS-1 before starting the app?**

I will do some more testing and let you know.

> **Arp Chord Scale Setting: I don't see any problem here, at first glance seems to work well on my unit.**

I'll re-test and see if I can reliable repro it.

> **Could you provide which OS and browser do you use?**

It was Brave Browser running on Win 10. I'll test in Chrome also and see if anything behaves differently.

**Comment by oscarrc** [comment]
Closed due to inactivity
