### ISSUE TITLE
Saving and loading memory banks

### ISSUE THREAD

**Issue by rael-albert** [oscarrc/nts-web#39]
1. Suppose I save memory bank number 5 (from Save > Current bank)
2. I restart the application and select memory bank number 0.
3.  Then I load memory bank number 5  (from File > Load bank) this is the memory bank I previously saved from step 1.

Does the application load it into memory bank 0 (the current selected memory bank) or do I have to select memory bank 5 to see it?

**Comment by oscarrc** [comment]
The application will load the bank in the currently selected memory bank.
