### ISSUE TITLE
404 errors with all "Install the app" download links on web UI

### ISSUE THREAD

**Issue by second-story** [oscarrc/nts-web#40]
Version: 3.0.0

As the title says, all web UI links to app installers throw 404 errors.  I first noticed this while trying to download the latest `.deb`, but it looks like all installer links point to an unavailable 3.0.1 version.  

I found that the `.deb` link worked after changing `web_linux-amd64-3.0.1.deb` to `web_linux-amd64-3.0.0.deb` at the end of the URL, so I'm sure the other links can be fixed in the same way.

**Comment by oscarrc** [comment]
Solved, thank you for noticing...
